name: "Setup"
runs:
  using: "composite"
  steps: 
    - name: Checkout repository
      uses: actions/checkout@v2
      with:
        fetch-depth: 2
    - run: git checkout HEAD^2
      if: ${{ github.event_name == 'pull_request' }}
    - name: Setup node
      uses: actions/setup-node@v1
